import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import os

def train_and_blend_projections():
    try:
        train_df = pd.read_csv('../data/historical_stats.csv')
        inference_df = pd.read_csv('../data/inference_stats.csv')
        espn_df = pd.read_csv('../data/projections.csv') # Generated by fetch_player_pool.py
    except FileNotFoundError:
        print("Required CSV files not found. Please run fetch_player_pool.py and data_pipeline.py first.")
        return

    features = [
        'passing_yards', 'passing_tds', 'interceptions',
        'rushing_yards', 'rushing_tds',
        'receptions', 'receiving_yards', 'receiving_tds',
        'fantasy_points_ppr', 'games'
    ]
    
    # Train separate models per position
    positions = ['QB', 'RB', 'WR', 'TE']
    ml_predictions = []
    
    for pos in positions:
        pos_train = train_df[train_df['position'] == pos].copy()
        pos_infer = inference_df[inference_df['position'] == pos].copy()
        
        if pos_train.empty or pos_infer.empty:
            continue
            
        # Basic imputation
        X_train = pos_train[features].fillna(0)
        y_train = pos_train['target_next_year_points']
        
        X_infer = pos_infer[features].fillna(0)
        
        # Train Random Forest
        model = RandomForestRegressor(n_estimators=100, random_state=42)
        model.fit(X_train, y_train)
        
        # Evaluate
        preds_train = model.predict(X_train)
        rmse = np.sqrt(mean_squared_error(y_train, preds_train))
        print(f"{pos} Model Trained. RMSE: {rmse:.2f}")
        
        # Predict
        pos_infer['ml_predicted_points'] = model.predict(X_infer)
        ml_predictions.append(pos_infer[['player_name', 'position', 'ml_predicted_points']])
        
    ml_preds_df = pd.concat(ml_predictions)
    
    # Merge ML predictions with ESPN baseline
    # Clean names for better matching (e.g., removing Jr., III, etc)
    def clean_name(name):
        if pd.isna(name): return ""
        return str(name).replace(' Jr.', '').replace(' Sr.', '').replace(' II', '').replace(' III', '').strip().lower()
        
    espn_df['match_name'] = espn_df['name'].apply(clean_name)
    ml_preds_df['match_name'] = ml_preds_df['player_name'].apply(clean_name)
    
    # Merge
    blended_df = espn_df.merge(ml_preds_df[['match_name', 'ml_predicted_points']], on='match_name', how='left')
    
    # Blend strategy: 50% ESPN, 50% ML (if ML exists)
    def calculate_blended(row):
        espn_pts = row.get('projected_points', 0)
        ml_pts = row.get('ml_predicted_points')
        
        if pd.isna(ml_pts):
            # Rookie or player without 2024 stats, just use ESPN
            return espn_pts
        else:
            # Blend
            return (espn_pts * 0.5) + (ml_pts * 0.5)
            
    blended_df['blended_projected_points'] = blended_df.apply(calculate_blended, axis=1)
    
    # Replace the projected_points column with our new blended points
    blended_df['projected_points'] = blended_df['blended_projected_points']
    
    # Cleanup
    blended_df = blended_df.drop(columns=['match_name', 'ml_predicted_points', 'blended_projected_points'])
    
    blended_df = blended_df.sort_values(by='projected_points', ascending=False)
    
    # Overwrite the projections.csv so the app uses our blended version
    blended_df.to_csv('../data/projections.csv', index=False)
    print(f"Successfully generated blended projections for {len(blended_df)} players and saved to ../data/projections.csv")

if __name__ == "__main__":
    train_and_blend_projections()
